// GERADO por scripts/gen-foods.ts a partir de "NUTRIX - BASE - REV 1.xlsx".
// Macros por 100 g = exatos da planilha da nutricionista. Medida caseira, porção,
// flags e grupo de substituição são inferidos por categoria + nome. NÃO editar à
// mão: rode "pnpm exec tsx scripts/gen-foods.ts" para regenerar.
import type { Alimento, Categoria } from "./foods";

const A = (
  nome: string, cat: Categoria, kcal: number, p: number, c: number, f: number,
  medida: string, gPorMedida: number,
  flags: { vegetariano: boolean; vegano: boolean; lactose: boolean; gluten: boolean },
): Alimento => ({ nome, cat, kcal, p, c, f, medida, gPorMedida, ...flags });

export const ALIMENTOS_BASE: Alimento[] = [
  A("Arroz branco", "carboidrato", 128, 2.5, 28.1, 0.2, "colher de sopa", 25, { vegetariano: true, vegano: true, lactose: false, gluten: false }),
  A("Arroz integral", "carboidrato", 124, 2.6, 25.8, 1, "colher de sopa", 25, { vegetariano: true, vegano: true, lactose: false, gluten: false }),
  A("Macarrão", "carboidrato", 157, 5.8, 30.9, 0.9, "colher de sopa", 25, { vegetariano: true, vegano: true, lactose: false, gluten: true }),
  A("Pão francês", "carboidrato", 260, 8, 58.6, 3.1, "unidade", 50, { vegetariano: true, vegano: true, lactose: false, gluten: true }),
  A("Pão de forma", "carboidrato", 253, 12, 44.1, 2.7, "fatia", 25, { vegetariano: true, vegano: true, lactose: false, gluten: true }),
  A("Pão integral", "carboidrato", 253, 9.4, 49.9, 3.7, "fatia", 25, { vegetariano: true, vegano: true, lactose: false, gluten: true }),
  A("Aveia em flocos", "carboidrato", 394, 13.9, 66.6, 8.5, "colher de sopa", 15, { vegetariano: true, vegano: true, lactose: false, gluten: true }),
  A("Granola", "carboidrato", 471, 10, 64, 18, "colher de sopa", 15, { vegetariano: true, vegano: true, lactose: false, gluten: false }),
  A("Cuscuz de milho", "carboidrato", 113, 2.2, 25.3, 0.7, "colher de sopa", 25, { vegetariano: true, vegano: true, lactose: false, gluten: false }),
  A("Tapioca sem recheio", "carboidrato", 232, 0.2, 57, 0.1, "unidade", 60, { vegetariano: true, vegano: true, lactose: false, gluten: false }),
  A("Beiju de tapioca", "carboidrato", 232, 0.2, 57, 0.1, "unidade", 60, { vegetariano: true, vegano: true, lactose: false, gluten: false }),
  A("Farinha de mandioca", "carboidrato", 365, 1.6, 89.2, 0.3, "colher de sopa", 15, { vegetariano: true, vegano: true, lactose: false, gluten: false }),
  A("Farinha d'água", "carboidrato", 350, 1.5, 85, 0.5, "colher de sopa", 15, { vegetariano: true, vegano: true, lactose: false, gluten: false }),
  A("Farinha de milho", "carboidrato", 351, 7.2, 79.1, 1.5, "colher de sopa", 15, { vegetariano: true, vegano: true, lactose: false, gluten: false }),
  A("Fubá de milho", "carboidrato", 353, 7.2, 78.9, 1.9, "colher de sopa", 15, { vegetariano: true, vegano: true, lactose: false, gluten: false }),
  A("Canjica/mungunzá de milho", "carboidrato", 112, 2.4, 24.9, 0.5, "colher de sopa", 25, { vegetariano: true, vegano: true, lactose: false, gluten: false }),
  A("Milho verde", "carboidrato", 98, 3.2, 20.9, 2.4, "espiga", 100, { vegetariano: true, vegano: true, lactose: false, gluten: false }),
  A("Polenta", "carboidrato", 103, 2.3, 23.3, 0.3, "colher de sopa", 25, { vegetariano: true, vegano: true, lactose: false, gluten: false }),
  A("Biscoito água e sal", "carboidrato", 424, 10, 68.7, 12, "unidade", 6, { vegetariano: true, vegano: true, lactose: false, gluten: true }),
  A("Biscoito de polvilho", "carboidrato", 438, 1.3, 80.5, 12.3, "unidade", 6, { vegetariano: true, vegano: true, lactose: false, gluten: false }),
  A("Batata inglesa", "carboidrato", 52, 1.2, 11.9, 0, "porção", 100, { vegetariano: true, vegano: true, lactose: false, gluten: false }),
  A("Batata-doce", "carboidrato", 77, 0.6, 18.4, 0.1, "porção", 100, { vegetariano: true, vegano: true, lactose: false, gluten: false }),
  A("Mandioca/macaxeira/aipim", "carboidrato", 125, 0.6, 30.1, 0.3, "porção", 100, { vegetariano: true, vegano: true, lactose: false, gluten: false }),
  A("Inhame", "carboidrato", 97, 2.1, 23.2, 0.2, "porção", 100, { vegetariano: true, vegano: true, lactose: false, gluten: false }),
  A("Cará", "carboidrato", 78, 1.5, 18.9, 0.1, "porção", 100, { vegetariano: true, vegano: true, lactose: false, gluten: false }),
  A("Jerimum/abóbora", "carboidrato", 48, 1.4, 10.8, 0.7, "porção", 100, { vegetariano: true, vegano: true, lactose: false, gluten: false }),
  A("Abóbora cabotiá", "carboidrato", 48, 1.4, 10.8, 0.7, "porção", 100, { vegetariano: true, vegano: true, lactose: false, gluten: false }),
  A("Beterraba", "carboidrato", 32, 1.3, 7.2, 0.1, "porção", 100, { vegetariano: true, vegano: true, lactose: false, gluten: false }),
  A("Cenoura", "carboidrato", 30, 0.8, 6.7, 0.2, "porção", 100, { vegetariano: true, vegano: true, lactose: false, gluten: false }),
  A("Feijão preto", "carboidrato", 77, 4.5, 14, 0.5, "concha", 80, { vegetariano: true, vegano: true, lactose: false, gluten: false }),
  A("Feijão carioca", "carboidrato", 76, 4.8, 13.6, 0.5, "concha", 80, { vegetariano: true, vegano: true, lactose: false, gluten: false }),
  A("Feijão verde", "carboidrato", 121, 6.2, 20.3, 1, "concha", 80, { vegetariano: true, vegano: true, lactose: false, gluten: false }),
  A("Feijão de corda/fradinho", "carboidrato", 78, 5.1, 13.5, 0.6, "concha", 80, { vegetariano: true, vegano: true, lactose: false, gluten: false }),
  A("Baião de dois", "carboidrato", 136, 6.2, 20.5, 3.4, "concha", 80, { vegetariano: true, vegano: true, lactose: false, gluten: false }),
  A("Lentilha", "carboidrato", 93, 6.3, 16.3, 0.5, "concha", 80, { vegetariano: true, vegano: true, lactose: false, gluten: false }),
  A("Grão-de-bico", "carboidrato", 164, 8.9, 27.4, 2.6, "concha", 80, { vegetariano: true, vegano: true, lactose: false, gluten: false }),
  A("Ervilha", "carboidrato", 81, 5.4, 14.5, 0.4, "concha", 80, { vegetariano: true, vegano: true, lactose: false, gluten: false }),
  A("Soja", "carboidrato", 173, 16.6, 9.9, 9, "concha", 80, { vegetariano: true, vegano: true, lactose: false, gluten: false }),
  A("Peito de frango", "proteina", 159, 32, 0, 2.5, "porção", 100, { vegetariano: false, vegano: false, lactose: false, gluten: false }),
  A("Frango desfiado", "proteina", 165, 31, 0, 3.5, "porção", 100, { vegetariano: false, vegano: false, lactose: false, gluten: false }),
  A("Coxa de frango sem pele", "proteina", 209, 28, 0, 10, "porção", 100, { vegetariano: false, vegano: false, lactose: false, gluten: false }),
  A("Patinho bovino", "proteina", 219, 35.9, 0, 7.3, "porção", 100, { vegetariano: false, vegano: false, lactose: false, gluten: false }),
  A("Patinho moído", "proteina", 208, 33.4, 0, 8.3, "porção", 100, { vegetariano: false, vegano: false, lactose: false, gluten: false }),
  A("Músculo bovino", "proteina", 194, 31.2, 0, 6.7, "porção", 100, { vegetariano: false, vegano: false, lactose: false, gluten: false }),
  A("Acém bovino", "proteina", 215, 27, 0, 11, "porção", 100, { vegetariano: false, vegano: false, lactose: false, gluten: false }),
  A("Coxão mole", "proteina", 219, 32.4, 0, 9, "porção", 100, { vegetariano: false, vegano: false, lactose: false, gluten: false }),
  A("Alcatra", "proteina", 241, 31.9, 0, 12, "porção", 100, { vegetariano: false, vegano: false, lactose: false, gluten: false }),
  A("Contrafilé sem gordura", "proteina", 194, 35.9, 0, 5, "porção", 100, { vegetariano: false, vegano: false, lactose: false, gluten: false }),
  A("Carne de sol", "proteina", 250, 37, 0, 11, "porção", 100, { vegetariano: false, vegano: false, lactose: false, gluten: false }),
  A("Charque/carne seca", "proteina", 249, 36.4, 0, 11.9, "porção", 100, { vegetariano: false, vegano: false, lactose: false, gluten: false }),
  A("Lombo suíno", "proteina", 210, 35.7, 0, 6.4, "porção", 100, { vegetariano: false, vegano: false, lactose: false, gluten: false }),
  A("Pernil suíno", "proteina", 262, 32, 0, 14, "porção", 100, { vegetariano: false, vegano: false, lactose: false, gluten: false }),
  A("Linguiça suína", "proteina", 296, 20, 2, 23, "porção", 100, { vegetariano: false, vegano: false, lactose: false, gluten: false }),
  A("Tilápia", "proteina", 128, 26, 0, 2.5, "porção", 100, { vegetariano: false, vegano: false, lactose: false, gluten: false }),
  A("Sardinha", "proteina", 164, 32, 0, 3, "porção", 100, { vegetariano: false, vegano: false, lactose: false, gluten: false }),
  A("Atum", "proteina", 184, 29.9, 0, 6.3, "porção", 100, { vegetariano: false, vegano: false, lactose: false, gluten: false }),
  A("Pescada", "proteina", 107, 23, 0, 1.2, "porção", 100, { vegetariano: false, vegano: false, lactose: false, gluten: false }),
  A("Tambaqui", "proteina", 210, 25, 0, 12, "porção", 100, { vegetariano: false, vegano: false, lactose: false, gluten: false }),
  A("Pirarucu", "proteina", 145, 30, 0, 2.5, "porção", 100, { vegetariano: false, vegano: false, lactose: false, gluten: false }),
  A("Tucunaré", "proteina", 150, 28, 0, 4, "porção", 100, { vegetariano: false, vegano: false, lactose: false, gluten: false }),
  A("Jaraqui", "proteina", 180, 26, 0, 8, "porção", 100, { vegetariano: false, vegano: false, lactose: false, gluten: false }),
  A("Filhote/piraíba", "proteina", 150, 27, 0, 4.5, "porção", 100, { vegetariano: false, vegano: false, lactose: false, gluten: false }),
  A("Camarão", "proteina", 99, 24, 0.2, 0.3, "porção", 100, { vegetariano: false, vegano: false, lactose: false, gluten: false }),
  A("Caranguejo", "proteina", 97, 19, 0, 2, "porção", 100, { vegetariano: false, vegano: false, lactose: false, gluten: false }),
  A("Ovo de galinha", "proteina", 146, 13.3, 0.6, 9.5, "unidade", 50, { vegetariano: true, vegano: false, lactose: false, gluten: false }),
  A("Ovo mexido", "proteina", 160, 15.6, 1.2, 18.6, "unidade", 50, { vegetariano: true, vegano: false, lactose: false, gluten: false }),
  A("Clara de ovo", "proteina", 52, 11, 0.7, 0.2, "unidade", 33, { vegetariano: true, vegano: false, lactose: false, gluten: false }),
  A("Ovo de codorna", "proteina", 177, 13.7, 0.8, 12.7, "unidade", 10, { vegetariano: true, vegano: false, lactose: false, gluten: false }),
  A("Leite integral", "proteina", 61, 3.2, 4.7, 3.3, "copo", 200, { vegetariano: true, vegano: false, lactose: true, gluten: false }),
  A("Leite semidesnatado", "proteina", 45, 3.3, 4.8, 1.6, "copo", 200, { vegetariano: true, vegano: false, lactose: true, gluten: false }),
  A("Leite desnatado", "proteina", 35, 3.4, 5, 0.2, "copo", 200, { vegetariano: true, vegano: false, lactose: true, gluten: false }),
  A("Iogurte natural integral", "proteina", 61, 3.5, 4.7, 3.3, "pote", 170, { vegetariano: true, vegano: false, lactose: true, gluten: false }),
  A("Iogurte desnatado", "proteina", 51, 4.1, 1.9, 3, "pote", 170, { vegetariano: true, vegano: false, lactose: true, gluten: false }),
  A("Queijo prato", "proteina", 360, 22.7, 1.9, 29.1, "fatia", 20, { vegetariano: true, vegano: false, lactose: true, gluten: false }),
  A("Queijo muçarela", "proteina", 330, 22.6, 3, 25.2, "fatia", 20, { vegetariano: true, vegano: false, lactose: true, gluten: false }),
  A("Queijo minas frescal", "proteina", 264, 17.4, 3.2, 20.2, "fatia", 20, { vegetariano: true, vegano: false, lactose: true, gluten: false }),
  A("Queijo coalho", "proteina", 321, 24.6, 3, 23.8, "fatia", 20, { vegetariano: true, vegano: false, lactose: true, gluten: false }),
  A("Requeijão cremoso", "proteina", 257, 9.6, 2.4, 23.4, "colher de sopa", 20, { vegetariano: true, vegano: false, lactose: true, gluten: false }),
  A("Ricota", "proteina", 140, 12.6, 3.8, 8.1, "fatia", 30, { vegetariano: true, vegano: false, lactose: true, gluten: false }),
  A("Banana prata", "fruta", 98, 1.3, 26, 0.1, "unidade", 80, { vegetariano: true, vegano: true, lactose: false, gluten: false }),
  A("Banana nanica", "fruta", 92, 1.4, 23.8, 0.1, "unidade", 80, { vegetariano: true, vegano: true, lactose: false, gluten: false }),
  A("Maçã", "fruta", 56, 0.3, 15.2, 0, "unidade", 130, { vegetariano: true, vegano: true, lactose: false, gluten: false }),
  A("Maçã argentina", "fruta", 63, 0.2, 16.6, 0.2, "unidade", 130, { vegetariano: true, vegano: true, lactose: false, gluten: false }),
  A("Laranja pera", "fruta", 37, 1, 8.9, 0.1, "unidade", 130, { vegetariano: true, vegano: true, lactose: false, gluten: false }),
  A("Laranja lima", "fruta", 46, 1.1, 11.5, 0.1, "unidade", 130, { vegetariano: true, vegano: true, lactose: false, gluten: false }),
  A("Mamão formosa", "fruta", 45, 0.8, 11.6, 0.1, "fatia", 150, { vegetariano: true, vegano: true, lactose: false, gluten: false }),
  A("Mamão papaia", "fruta", 40, 0.5, 10.4, 0.1, "fatia", 150, { vegetariano: true, vegano: true, lactose: false, gluten: false }),
  A("Manga", "fruta", 72, 0.4, 19.4, 0.2, "unidade", 120, { vegetariano: true, vegano: true, lactose: false, gluten: false }),
  A("Melancia", "fruta", 33, 0.9, 8.1, 0, "fatia", 200, { vegetariano: true, vegano: true, lactose: false, gluten: false }),
  A("Melão", "fruta", 29, 0.7, 7.5, 0, "fatia", 150, { vegetariano: true, vegano: true, lactose: false, gluten: false }),
  A("Abacaxi", "fruta", 48, 0.9, 12.3, 0.1, "fatia", 100, { vegetariano: true, vegano: true, lactose: false, gluten: false }),
  A("Morango", "fruta", 30, 0.9, 6.8, 0.3, "porção", 100, { vegetariano: true, vegano: true, lactose: false, gluten: false }),
  A("Uva", "fruta", 53, 0.7, 13.6, 0.2, "porção", 100, { vegetariano: true, vegano: true, lactose: false, gluten: false }),
  A("Pera", "fruta", 53, 0.6, 14, 0.1, "unidade", 130, { vegetariano: true, vegano: true, lactose: false, gluten: false }),
  A("Goiaba vermelha", "fruta", 54, 1.1, 13, 0.4, "unidade", 100, { vegetariano: true, vegano: false, lactose: false, gluten: false }),
  A("Maracujá", "fruta", 68, 2, 12.3, 2.1, "porção", 100, { vegetariano: true, vegano: true, lactose: false, gluten: false }),
  A("Acerola", "fruta", 33, 0.9, 8, 0.2, "porção", 100, { vegetariano: true, vegano: true, lactose: false, gluten: false }),
  A("Caju", "fruta", 43, 1, 10.3, 0.3, "porção", 100, { vegetariano: true, vegano: true, lactose: false, gluten: false }),
  A("Cajá", "fruta", 46, 0.8, 11.4, 0.2, "porção", 100, { vegetariano: true, vegano: true, lactose: false, gluten: false }),
  A("Umbu", "fruta", 37, 0.8, 9.4, 0, "porção", 100, { vegetariano: true, vegano: true, lactose: false, gluten: false }),
  A("Siriguela", "fruta", 76, 1.4, 18.9, 0.4, "porção", 100, { vegetariano: true, vegano: true, lactose: false, gluten: false }),
  A("Graviola", "fruta", 62, 0.8, 15.8, 0.2, "porção", 100, { vegetariano: true, vegano: true, lactose: false, gluten: false }),
  A("Pitanga", "fruta", 41, 0.9, 10.2, 0.2, "porção", 100, { vegetariano: true, vegano: true, lactose: false, gluten: false }),
  A("Jaca", "fruta", 88, 1.4, 22.5, 0.3, "porção", 100, { vegetariano: true, vegano: true, lactose: false, gluten: false }),
  A("Tamarindo", "fruta", 276, 3.2, 72.5, 0.5, "porção", 100, { vegetariano: true, vegano: true, lactose: false, gluten: false }),
  A("Açaí", "fruta", 58, 0.8, 6.2, 3.9, "porção", 100, { vegetariano: true, vegano: true, lactose: false, gluten: false }),
  A("Cupuaçu", "fruta", 49, 1.2, 10.4, 1, "porção", 100, { vegetariano: true, vegano: true, lactose: false, gluten: false }),
  A("Bacuri", "fruta", 105, 1.9, 22.8, 1.6, "porção", 100, { vegetariano: true, vegano: true, lactose: false, gluten: false }),
  A("Taperebá/cajá", "fruta", 46, 0.8, 11.4, 0.2, "porção", 100, { vegetariano: true, vegano: true, lactose: false, gluten: false }),
  A("Muruci", "fruta", 47, 0.8, 12, 0.2, "porção", 100, { vegetariano: true, vegano: true, lactose: false, gluten: false }),
  A("Buriti", "fruta", 145, 1.8, 12.5, 10.9, "porção", 100, { vegetariano: true, vegano: true, lactose: false, gluten: false }),
  A("Tucumã", "fruta", 262, 2.1, 26.5, 19.1, "porção", 100, { vegetariano: true, vegano: true, lactose: false, gluten: false }),
  A("Pupunha", "fruta", 194, 2.5, 29.6, 7.5, "porção", 100, { vegetariano: true, vegano: true, lactose: false, gluten: false }),
  A("Castanha-do-pará", "fruta", 643, 14.5, 15.1, 63.5, "unidade", 5, { vegetariano: true, vegano: true, lactose: false, gluten: false }),
  A("Alface", "vegetal", 15, 1.4, 2.9, 0.2, "porção", 40, { vegetariano: true, vegano: true, lactose: false, gluten: false }),
  A("Tomate", "vegetal", 15, 1.1, 3.1, 0.2, "porção", 60, { vegetariano: true, vegano: true, lactose: false, gluten: false }),
  A("Pepino", "vegetal", 10, 0.9, 2, 0, "porção", 60, { vegetariano: true, vegano: true, lactose: false, gluten: false }),
  A("Repolho", "vegetal", 17, 0.9, 3.9, 0.1, "porção", 40, { vegetariano: true, vegano: true, lactose: false, gluten: false }),
  A("Couve", "vegetal", 90, 2.9, 8.7, 5, "porção", 40, { vegetariano: true, vegano: true, lactose: false, gluten: false }),
  A("Brócolis", "vegetal", 25, 2.1, 4.4, 0.5, "porção", 60, { vegetariano: true, vegano: true, lactose: false, gluten: false }),
  A("Couve-flor", "vegetal", 19, 1.2, 3.9, 0.3, "porção", 40, { vegetariano: true, vegano: true, lactose: false, gluten: false }),
  A("Abobrinha", "vegetal", 15, 1.1, 3, 0.2, "porção", 60, { vegetariano: true, vegano: true, lactose: false, gluten: false }),
  A("Quiabo", "vegetal", 22, 1.9, 4.5, 0.2, "porção", 60, { vegetariano: true, vegano: true, lactose: false, gluten: false }),
  A("Maxixe", "vegetal", 14, 1.4, 2.7, 0.1, "porção", 60, { vegetariano: true, vegano: true, lactose: false, gluten: false }),
  A("Vinagreira", "vegetal", 31, 2, 5, 0.5, "porção", 40, { vegetariano: true, vegano: true, lactose: false, gluten: false }),
  A("Jambu", "vegetal", 20, 2, 3, 0.3, "porção", 40, { vegetariano: true, vegano: true, lactose: false, gluten: false }),
  A("Chicória-do-Pará", "vegetal", 23, 1.7, 4, 0.4, "porção", 40, { vegetariano: true, vegano: true, lactose: false, gluten: false }),
  A("Palmito", "vegetal", 23, 1.8, 4.3, 0.4, "porção", 60, { vegetariano: true, vegano: true, lactose: false, gluten: false }),
  A("Amendoim", "gordura", 606, 22.5, 18.7, 54, "porção", 25, { vegetariano: true, vegano: true, lactose: false, gluten: false }),
  A("Castanha de caju", "gordura", 570, 18.5, 29.1, 46.3, "porção", 25, { vegetariano: true, vegano: true, lactose: false, gluten: false }),
  A("Coco seco", "gordura", 406, 3.7, 10.4, 42, "colher de sopa", 20, { vegetariano: true, vegano: true, lactose: false, gluten: false }),
  A("Coco verde", "gordura", 80, 1.5, 10.4, 4.5, "colher de sopa", 20, { vegetariano: true, vegano: true, lactose: false, gluten: false }),
  A("Chia", "gordura", 486, 16.5, 42.1, 30.7, "colher de sopa", 12, { vegetariano: true, vegano: true, lactose: false, gluten: false }),
  A("Linhaça", "gordura", 534, 18.3, 28.9, 42.2, "colher de sopa", 12, { vegetariano: true, vegano: true, lactose: false, gluten: false }),
  A("Azeite de oliva", "gordura", 884, 0, 0, 100, "colher de sopa", 8, { vegetariano: true, vegano: true, lactose: false, gluten: false }),
  A("Óleo de soja", "gordura", 884, 0, 0, 100, "colher de sopa", 8, { vegetariano: true, vegano: true, lactose: false, gluten: false }),
  A("Azeite de dendê", "gordura", 884, 0, 0, 100, "colher de sopa", 8, { vegetariano: true, vegano: true, lactose: false, gluten: false }),
  A("Manteiga", "gordura", 717, 0.9, 0.1, 81.1, "colher de chá", 8, { vegetariano: true, vegano: true, lactose: false, gluten: false }),
  A("Margarina", "gordura", 596, 0.4, 0.7, 67.4, "colher de chá", 8, { vegetariano: true, vegano: true, lactose: false, gluten: false }),
  A("Acarajé", "gordura", 289, 8.3, 29.1, 15.5, "porção", 25, { vegetariano: false, vegano: false, lactose: false, gluten: false }),
  A("Vatapá", "gordura", 255, 6, 13, 20, "porção", 25, { vegetariano: false, vegano: false, lactose: false, gluten: false }),
  A("Caruru", "gordura", 107, 3.5, 9.5, 6.5, "porção", 25, { vegetariano: false, vegano: false, lactose: false, gluten: false }),
  A("Moqueca de peixe", "gordura", 145, 15, 4, 8, "porção", 25, { vegetariano: false, vegano: false, lactose: false, gluten: false }),
  A("Escondidinho de carne seca", "carboidrato", 190, 10, 20, 8, "colher de sopa", 25, { vegetariano: false, vegano: false, lactose: false, gluten: false }),
  A("Paçoca de carne de sol", "gordura", 330, 25, 22, 16, "porção", 25, { vegetariano: false, vegano: false, lactose: false, gluten: false }),
  A("Rubacão", "carboidrato", 155, 7, 20, 5.5, "colher de sopa", 25, { vegetariano: false, vegano: false, lactose: false, gluten: false }),
  A("Arroz de cuxá", "carboidrato", 145, 3, 25, 4, "colher de sopa", 25, { vegetariano: false, vegano: false, lactose: false, gluten: false }),
  A("Tacacá", "carboidrato", 65, 3, 10, 1.5, "colher de sopa", 25, { vegetariano: false, vegano: false, lactose: false, gluten: false }),
  A("Pato no tucupi", "gordura", 190, 20, 3, 10, "porção", 25, { vegetariano: false, vegano: false, lactose: false, gluten: false }),
  A("Maniçoba", "gordura", 190, 13, 8, 12, "porção", 25, { vegetariano: false, vegano: false, lactose: false, gluten: false }),
  A("Caldeirada de peixe", "proteina", 110, 15, 5, 3.5, "porção", 100, { vegetariano: false, vegano: false, lactose: false, gluten: false }),
  A("X-caboquinho", "carboidrato", 280, 10, 30, 13, "colher de sopa", 25, { vegetariano: false, vegano: false, lactose: false, gluten: false }),
  A("Açúcar refinado", "carboidrato", 387, 0, 99.5, 0, "colher de sopa", 25, { vegetariano: true, vegano: true, lactose: false, gluten: false }),
  A("Mel", "carboidrato", 309, 0.3, 84, 0, "colher de sopa", 25, { vegetariano: true, vegano: false, lactose: false, gluten: false }),
  A("Goiabada", "carboidrato", 309, 0.4, 78.7, 0.1, "colher de sopa", 25, { vegetariano: true, vegano: true, lactose: false, gluten: false }),
  A("Doce de leite", "carboidrato", 306, 5.5, 59.5, 6, "colher de sopa", 25, { vegetariano: true, vegano: false, lactose: true, gluten: false }),
  A("Rapadura", "carboidrato", 352, 0.6, 90.8, 0.1, "colher de sopa", 25, { vegetariano: true, vegano: true, lactose: false, gluten: false }),
  A("Paçoca de amendoim", "gordura", 487, 16, 52, 24, "porção", 25, { vegetariano: true, vegano: false, lactose: false, gluten: false }),
  A("Pé-de-moleque", "carboidrato", 503, 13, 59, 24, "colher de sopa", 25, { vegetariano: true, vegano: false, lactose: false, gluten: false }),
  A("Cocada", "carboidrato", 405, 2, 63, 17, "colher de sopa", 25, { vegetariano: true, vegano: false, lactose: false, gluten: false }),
  A("Bolo de macaxeira", "carboidrato", 300, 4, 45, 12, "colher de sopa", 25, { vegetariano: true, vegano: false, lactose: false, gluten: true }),
  A("Bolo de milho", "carboidrato", 311, 5, 50, 10, "colher de sopa", 25, { vegetariano: true, vegano: false, lactose: false, gluten: true }),
  A("Cuscuz de tapioca", "carboidrato", 240, 3, 45, 6, "unidade", 60, { vegetariano: true, vegano: true, lactose: false, gluten: false }),
  A("Café sem açúcar", "bebida", 2, 0.1, 0, 0, "copo", 200, { vegetariano: true, vegano: true, lactose: false, gluten: false }),
  A("Água de coco", "bebida", 22, 0, 5.3, 0, "copo", 200, { vegetariano: true, vegano: true, lactose: false, gluten: false }),
  A("Suco de laranja natural", "bebida", 45, 0.7, 10.4, 0.2, "copo", 200, { vegetariano: true, vegano: true, lactose: false, gluten: false }),
  A("Suco de acerola", "bebida", 30, 0.4, 7, 0.1, "copo", 200, { vegetariano: true, vegano: true, lactose: false, gluten: false }),
  A("Suco de caju", "bebida", 38, 0.4, 9, 0.1, "copo", 200, { vegetariano: true, vegano: true, lactose: false, gluten: false }),
  A("Suco de cupuaçu", "bebida", 45, 0.5, 10, 0.3, "copo", 200, { vegetariano: true, vegano: true, lactose: false, gluten: false }),
];

// Grupo de substituição de cada alimento da base (troca só dentro do grupo).
export const GRUPO_BASE: Record<string, string> = {
  "Arroz branco": "carbo_prato",
  "Arroz integral": "carbo_prato",
  "Macarrão": "carbo_prato",
  "Pão francês": "carbo_pao",
  "Pão de forma": "carbo_pao",
  "Pão integral": "carbo_pao",
  "Aveia em flocos": "carbo_pao",
  "Granola": "carbo_pao",
  "Cuscuz de milho": "carbo_pao",
  "Tapioca sem recheio": "carbo_pao",
  "Beiju de tapioca": "carbo_pao",
  "Farinha de mandioca": "carbo_prato",
  "Farinha d'água": "carbo_prato",
  "Farinha de milho": "carbo_prato",
  "Fubá de milho": "carbo_prato",
  "Canjica/mungunzá de milho": "carbo_prato",
  "Milho verde": "carbo_prato",
  "Polenta": "carbo_prato",
  "Biscoito água e sal": "carbo_pao",
  "Biscoito de polvilho": "carbo_pao",
  "Batata inglesa": "carbo_prato",
  "Batata-doce": "carbo_prato",
  "Mandioca/macaxeira/aipim": "carbo_prato",
  "Inhame": "carbo_prato",
  "Cará": "carbo_prato",
  "Jerimum/abóbora": "carbo_prato",
  "Abóbora cabotiá": "carbo_prato",
  "Beterraba": "carbo_prato",
  "Cenoura": "carbo_prato",
  "Feijão preto": "carbo_prato",
  "Feijão carioca": "carbo_prato",
  "Feijão verde": "carbo_prato",
  "Feijão de corda/fradinho": "carbo_prato",
  "Baião de dois": "carbo_prato",
  "Lentilha": "carbo_prato",
  "Grão-de-bico": "carbo_prato",
  "Ervilha": "carbo_prato",
  "Soja": "carbo_prato",
  "Peito de frango": "carne",
  "Frango desfiado": "carne",
  "Coxa de frango sem pele": "carne",
  "Patinho bovino": "carne",
  "Patinho moído": "carne",
  "Músculo bovino": "carne",
  "Acém bovino": "carne",
  "Coxão mole": "carne",
  "Alcatra": "carne",
  "Contrafilé sem gordura": "carne",
  "Carne de sol": "carne",
  "Charque/carne seca": "carne",
  "Lombo suíno": "carne",
  "Pernil suíno": "carne",
  "Linguiça suína": "carne",
  "Tilápia": "carne",
  "Sardinha": "carne",
  "Atum": "carne",
  "Pescada": "carne",
  "Tambaqui": "carne",
  "Pirarucu": "carne",
  "Tucunaré": "carne",
  "Jaraqui": "carne",
  "Filhote/piraíba": "carne",
  "Camarão": "carne",
  "Caranguejo": "carne",
  "Ovo de galinha": "prot_leve",
  "Ovo mexido": "prot_leve",
  "Clara de ovo": "prot_leve",
  "Ovo de codorna": "prot_leve",
  "Leite integral": "prot_leve",
  "Leite semidesnatado": "prot_leve",
  "Leite desnatado": "prot_leve",
  "Iogurte natural integral": "prot_leve",
  "Iogurte desnatado": "prot_leve",
  "Queijo prato": "prot_leve",
  "Queijo muçarela": "prot_leve",
  "Queijo minas frescal": "prot_leve",
  "Queijo coalho": "prot_leve",
  "Requeijão cremoso": "prot_leve",
  "Ricota": "prot_leve",
  "Banana prata": "fruta",
  "Banana nanica": "fruta",
  "Maçã": "fruta",
  "Maçã argentina": "fruta",
  "Laranja pera": "fruta",
  "Laranja lima": "fruta",
  "Mamão formosa": "fruta",
  "Mamão papaia": "fruta",
  "Manga": "fruta",
  "Melancia": "fruta",
  "Melão": "fruta",
  "Abacaxi": "fruta",
  "Morango": "fruta",
  "Uva": "fruta",
  "Pera": "fruta",
  "Goiaba vermelha": "fruta",
  "Maracujá": "fruta",
  "Acerola": "fruta",
  "Caju": "fruta",
  "Cajá": "fruta",
  "Umbu": "fruta",
  "Siriguela": "fruta",
  "Graviola": "fruta",
  "Pitanga": "fruta",
  "Jaca": "fruta",
  "Tamarindo": "fruta",
  "Açaí": "fruta",
  "Cupuaçu": "fruta",
  "Bacuri": "fruta",
  "Taperebá/cajá": "fruta",
  "Muruci": "fruta",
  "Buriti": "fruta",
  "Tucumã": "fruta",
  "Pupunha": "fruta",
  "Castanha-do-pará": "fruta",
  "Alface": "vegetal",
  "Tomate": "vegetal",
  "Pepino": "vegetal",
  "Repolho": "vegetal",
  "Couve": "vegetal",
  "Brócolis": "vegetal",
  "Couve-flor": "vegetal",
  "Abobrinha": "vegetal",
  "Quiabo": "vegetal",
  "Maxixe": "vegetal",
  "Vinagreira": "vegetal",
  "Jambu": "vegetal",
  "Chicória-do-Pará": "vegetal",
  "Palmito": "vegetal",
  "Amendoim": "gordura_pura",
  "Castanha de caju": "gordura_pura",
  "Coco seco": "gordura_pura",
  "Coco verde": "gordura_pura",
  "Chia": "gordura_pura",
  "Linhaça": "gordura_pura",
  "Azeite de oliva": "gordura_pura",
  "Óleo de soja": "gordura_pura",
  "Azeite de dendê": "gordura_pura",
  "Manteiga": "gordura_pura",
  "Margarina": "gordura_pura",
  "Acarajé": "prato_regional",
  "Vatapá": "prato_regional",
  "Caruru": "prato_regional",
  "Moqueca de peixe": "prato_regional",
  "Escondidinho de carne seca": "prato_regional",
  "Paçoca de carne de sol": "prato_regional",
  "Rubacão": "prato_regional",
  "Arroz de cuxá": "prato_regional",
  "Tacacá": "prato_regional",
  "Pato no tucupi": "prato_regional",
  "Maniçoba": "prato_regional",
  "Caldeirada de peixe": "prato_regional",
  "X-caboquinho": "prato_regional",
  "Açúcar refinado": "doce",
  "Mel": "doce",
  "Goiabada": "doce",
  "Doce de leite": "doce",
  "Rapadura": "doce",
  "Paçoca de amendoim": "doce",
  "Pé-de-moleque": "doce",
  "Cocada": "doce",
  "Bolo de macaxeira": "doce",
  "Bolo de milho": "doce",
  "Cuscuz de tapioca": "doce",
  "Café sem açúcar": "bebida",
  "Água de coco": "bebida",
  "Suco de laranja natural": "bebida",
  "Suco de acerola": "bebida",
  "Suco de caju": "bebida",
  "Suco de cupuaçu": "bebida",
};
